### ISSUE TITLE
show this error when connected with atlas cluster 

### ISSUE THREAD

**Issue by sankalpdeveloper** [sujitpatil72/MongoDB-Client-Side-Field-Level-Encryption#3]
readError occurred: MongoServerError: BSON field 'FindCommandRequest.jsonSchema' is an unknown field. This command may be meant for a mongocryptd process.
    at Connection.onMessage (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\connection.js:202:30)
    at MessageStream.<anonymous> (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\connection.js:62:60)
    at MessageStream.emit (node:events:527:28)
    at processIncomingData (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\message_stream.js:108:16)
    at MessageStream._write (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\message_stream.js:28:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:527:28) {
  ok: 0,
  code: 4662500,
  codeName: 'Location4662500',
  '$clusterTime': {
    clusterTime: new Timestamp({ t: 1652331538, i: 8 }),
    signature: {
      hash: new Binary(Buffer.from("3ebd84e5424189ead113b43c8681bc4c2caef2c5", "hex"), 0),
      keyId: new Long("7051624022655631366")
    }
  },
  operationTime: new Timestamp({ t: 1652331538, i: 7 }),
  [Symbol(errorLabels)]: Set(0) {}
}
writeError occurred: MongoServerError: BSON field 'insert.jsonSchema' is an unknown field. This command may be meant for a mongocryptd process.
    at Connection.onMessage (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\connection.js:202:30)
    at MessageStream.<anonymous> (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\connection.js:62:60)
    at MessageStream.emit (node:events:527:28)
    at processIncomingData (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\message_stream.js:108:16)
    at MessageStream._write (D:\cse\MongoDB-Client-Side-Field-Level-Encryption-main\node_modules\mongodb\lib\cmap\message_stream.js:28:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:527:28) {
  ok: 0,
  code: 4662500,
  codeName: 'Location4662500',

  '$clusterTime': {
    clusterTime: new Timestamp({ t: 1652331538, i: 8 }),
    signature: {
      hash: new Binary(Buffer.from("3ebd84e5424189ead113b43c8681bc4c2caef2c5", "hex"), 0),
      keyId: new Long("7051624022655631366")
    }
  },
  operationTime: new Timestamp({ t: 1652331536, i: 9 }),
  [Symbol(errorLabels)]: Set(0) {}
}

**Comment by sankalpdeveloper** [comment]
can you show an example of how to use it with mongoose

**Comment by Shaedul** [comment]
Hello, I am also facing difficulties when running `node app.js`
Can you help me, how can I overcome this:
Thanks in advance

writeError occurred: MongoServerError: BSON field 'insert.jsonSchema' is an unknown field. This command may be meant for a mongocryptd process.
    at Connection.onMessage (/home/shahed/Documents/encryptionDemo/node_modules/mongodb/lib/cmap/connection.js:230:30)
    at MessageStream.<anonymous> (/home/shahed/Documents/encryptionDemo/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/home/shahed/Documents/encryptionDemo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/home/shahed/Documents/encryptionDemo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28) {
  ok: new Double(0.0),
  code: new Int32(4662500),
  codeName: 'Location4662500',
  [Symbol(errorLabels)]: Set(0) {}

@sankalpdeveloper
